version: '3.3'
services:
  postgis:
    image: postgis/postgis
    container_name: jodd_postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=geodb
    ports:
      - 5434:5432
    volumes:
      - ./postgis:/docker-entrypoint-initdb.d
  nodejs:
    image: node
    container_name: jodd_nodejs
    working_dir: /app/nodejs
    restart: always
    depends_on:
      - postgis
    environment:
      - NODE_ENV=production
    volumes:
      - ./nodejs:/app/nodejs
    ports:
      - 80:3000
    command: bash -c "npm i && npm i -g nodemon && npm i -g pm2 && nodemon server.js"
